modLoader="javafml" #mandatory
loaderVersion="[28,)" #mandatory (28 is current forge version)
issueTrackerURL="https://github.com/ayamitsu0321/You-are-the-Squid/issues" #optional
[[mods]] #mandatory
modId="ayamitsu0321_urtsquid" #mandatory
version="${version}" #mandatory
displayName="URTSquid Mod" #mandatory
#updateJSONURL="" #optional
displayURL="https://github.com/ayamitsu0321/You-are-the-Squid/" #optional
#logoFile="" #optional
credits="Thanks for this mod goes to Java" #optional
authors="ayamitsu0321" #optional
description='''
かの偉人は言いました。
「ｲｶｶﾜｲｲﾃﾞｽ」
と。
'''

[[dependencies.ayamitsu0321_urtsquid]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[28,)" #mandatory
    ordering="NONE"
    side="BOTH"

[[dependencies.ayamitsu0321_urtsquid]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.14.4]"
    ordering="NONE"
    side="BOTH"
